export default {
    id: {
        ref: 'id',
        value: 0,
        required: true,
        type: 'internal',
        format: 'DDMMYYYY####',
        label: 'ID',
        placeholder: 'id',
        show: false,
    },
    firstName: {
        ref: 'firstName',
        value: '',
        required: true,
        type: 'text',
        format: 'text',
        label: 'First Name',
        placeholder: 'Full Name',
        show: true,
    },
    guardiansirName: {
        ref: 'guardiansirName',
        value: '',
        required: false,
        type: 'text',
        format: 'text',
        label: 'Guardian`s Name',
        placeholder: 'Guardian`s Name',
        show: true,
    },
    email: {
        ref: 'email',
        value: '',
        required: false,
        type: 'e-mail',
        format: 'something@example.com',
        label: 'Email',
        placeholder: 'something@example.com',
        show: true,
    },
    contact: {
        ref: 'contact',
        value: '',
        required: false,
        type: 'text',
        format: ['03xx-xxxxxxx', 'xxxxxxx'],
        label: 'Contact',
        placeholder: '03xx-xxxxxxx',
        show: true,
    },
    city: {
        ref: 'city',
        value: '',
        required: false,
        label: 'City',
        placeholder: 'City',
        show: true,
        type: 'text',
    },
    gender: {
        ref: 'gender',
        props: {
            heading: 'Gender',
            values: ['Male', 'Female', 'Other'],
            label: 'Gender',
        },
        required: true,
        type: 'drop-down',
        show: true,
        label: 'Gender'
    },
    timeOfReg: {
        ref: 'timeOfReg',
        value: '',
        required: true,
        type: 'internal',
        format: ['DD/MM/YYYY'],
        label: 'Time of Registration',
        placeholder: 'DD/MM/YYYY',
        show: false,
    },
    cnic: {
        ref: 'cnic',
        value: '',
        required: false,
        type: 'text',
        format: '#####-#######-#',
        label: 'CNIC',
        placeholder: '#####-#######-#',
        show: true,
    },
    biometric: {
        ref: 'biometric',
        value: '',
        required: false,
        type: 'biomatric',
        format: '',
        label: 'BIOMETRIC',
        placeholder: 'Biometric',
        show: false,
    },
}