const DUMMY_PATIENTS = [
    {
        checkupId: '0000',
        patientId: '0000',
        name: 'Arsalan Ahmed',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        gender: 'male',
        queue: 3,
        contact: '0321-12312312',
        checkup: true,
        awaitingPrescription: true,
    },
    {
        checkupId: '0001',
        patientId: '0000',
        name: 'Ms Anjum',
        doctor: 'Dr. Nabeela Khan',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 4,
        gender: 'female',
        contact: '0332-12312312',
        checkup: true,
        awaitingPrescription: false,
    },
    {
        checkupId: '0002',
        patientId: '0000',
        name: 'Abdullah Bhatti',
        doctor: 'Dr. Nabeela Khan',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 5,
        gender: 'male',
        contact: '0332-21122321',
        checkup: true,
        awaitingPrescription: false,
    },
    {
        checkupId: '0003',
        patientId: '0000',
        name: 'Asad Bhatti',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 6,
        gender: 'male',
        contact: '0321-23322222',
        checkup: true,
        awaitingPrescription: false,
    },
    {
        checkupId: '0004',
        patientId: '0000',
        name: 'Nimrah Asad',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 7,
        gender: 'female',
        contact: '0333-55555555',
        checkup: true,
        awaitingPrescription: false,

    },
    {
        checkupId: '0000',
        patientId: '0000',
        name: 'Arsalan Ahmed',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        gender: 'male',
        queue: 3,
        contact: '0321-12312312',
        checkup: false,
        awaitingPrescription: false,

    },
    {
        checkupId: '0001',
        patientId: '0000',
        name: 'Ms Anjum',
        doctor: 'Dr. Nabeela Khan',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 4,
        gender: 'female',
        contact: '0332-12312312',
        checkup: false,
        awaitingPrescription: false,

    },
    {
        checkupId: '0002',
        patientId: '0000',
        name: 'Abdullah Bhatti',
        doctor: 'Dr. Nabeela Khan',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 5,
        gender: 'male',
        contact: '0332-21122321',
        checkup: false,
        awaitingPrescription: false,

    },
    {
        checkupId: '0003',
        patientId: '0000',
        name: 'Asad Bhatti',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 6,
        gender: 'male',
        contact: '0321-23322222',
        checkup: false,
        awaitingPrescription: false,

    },
    {
        checkupId: '0004',
        patientId: '0000',
        name: 'Nimrah Asad',
        doctor: 'Dr. Saiqa Mukhtar',
        service: 'General Checkup',
        paymentStatus: 'paid',
        appointmentTime: '08/07/2021/16:42:42',
        queue: 7,
        gender: 'female',
        contact: '0333-55555555',
        checkup: false,
        awaitingPrescription: false,

    },
]


export default DUMMY_PATIENTS
