const patients = [
    {
        id: 0,
        fullName: 'Mumtaz Arshad',
        email: '',
        contact: '0345-5652541',
        city: 'Rawalpindi',
        gender: 'Female',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    },

    {
        id: 1,
        fullName: 'Danyal Zahid',
        email: 'danyal_zahid@gmail.com',
        contact: '0334-9551901',
        city: 'Rawalpindi',
        gender: 'Male',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    },
    {
        id: 2,
        fullName: 'Hammad Khan',
        email: 'hammadkhan92@gmail.com',
        contact: '03322532138',
        city: '',
        gender: 'Male',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    }, {
        id: 3,
        fullName: 'Ahmed Salman',
        email: 'ahmedsalman32@gmail.com',
        contact: '0321-4561237',
        city: 'Rawalpindi',
        gender: 'Male',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    }, {
        id: 4,
        fullName: 'Tehmina Gul',
        email: 'tehmina@yahoo.com',
        contact: '',
        city: 'Rawalpindi',
        gender: 'Female',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    }, {
        id: 5,
        fullName: 'Nimrah Asad',
        email: 'thedynamicminion@gmail.com',
        contact: '0316-5475407',
        city: 'Lahore',
        gender: 'Female',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    }, {
        id: 6,
        fullName: 'Asad Bhatti',
        email: 'bhatti.asad99@gmail.com',
        contact: '0345-4554875',
        city: 'Rawalpindi',
        gender: 'Male',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    }, {
        id: 7,
        fullName: 'Danyal Shahid',
        email: '',
        contact: '0345-4514874',
        city: 'Rawalpindi',
        gender: 'Male',
        timeOfReg: '',
        cnic: '',
        biometric: '',
    },
]

export default patients